spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl
spring.datasource.username=c##shayan
spring.datasource.password=shayan6421
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

recaptcha.secret=6LcWs34rAAAAACycqE7J4wLy2YH1DH7ganuTsaAT

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dowlatshahis1382@gmail.com
spring.mail.password=sudt zqik xbck uboq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
from.email=dowlatshahis1382@gmail.com
app.frontend.url=http://localhost:8080

jwt.secret=PSHpHmDHk4dSIeZ5gLLN06M+UIoqY7EcW2W0/ep2EHo=

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=thedarksoul82$@
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mycert
