spring.application.name=Home_Service
spring.datasource.url=jdbc:postgresql://localhost:5432/home_service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
recaptcha.secret=6LcWs34rAAAAACycqE7J4wLy2YH1DH7ganuTsaAT