spring.application.name=Home_Service
spring.datasource.url=jdbc:postgresql://localhost:5432/home_service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
recaptcha.secret=6LcWs34rAAAAACycqE7J4wLy2YH1DH7ganuTsaAT

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dowlatshahis1382@gmail.com
spring.mail.password=sudt zqik xbck uboq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
from.email=dowlatshahis1382@gmail.com
app.frontend.url=http://localhost:8080

jwt.secret=PSHpHmDHk4dSIeZ5gLLN06M+UIoqY7EcW2W0/ep2EHo=

